name: Merge Development to Main

on:
  push:
    branches:
      - development

jobs:
  merge_to_main:
    runs-on: ubuntu-latest

    outputs:
      steps: ${{ toJson(steps) }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Pull Request
      id: create_pr
      uses: actions/github-script@v5
      with:
        script: |
          const pr = await context.github.pulls.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: 'Merge development to main',
            head: 'development',
            base: 'main',
            changes: [],
          });

          console.log(`Pull request created: ${pr.data.html_url}`);

          // Set output for the next step
          return { pull_request_number: pr.data.number };

    - name: Merge Pull Request
      uses: actions/github-script@v5
      with:
        script: |
          // Get the output from the previous step
          const prNumber = parseInt(steps.create_pr.outputs.pull_request_number);

          await context.github.pulls.merge({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: prNumber,
          });

          console.log(`Pull request merged successfully.`);