name: Merge Development to Main

on:
  push:
    branches:
      - development

jobs:
  merge_to_main:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Pull Request
      uses: actions/github-script@v5
      with:
        script: |
          const pr = await context.github.pulls.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: 'Merge development to main',
            head: 'development',
            base: 'main',
            changes: [],
          });
    
          console.log(`Pull request created: ${pr.data.html_url}`);
    
    - name: Merge Pull Request
      uses: actions/github-script@v5
      with:
        script: |
          await context.github.pulls.merge({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: pr.data.number,
          });
    
          console.log(`Pull request merged successfully.`);
    