name: Merge Development to Main

on:
  push:
    branches:
      - development

jobs:
  merge_to_main:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Pull Request
      id: create_pr
      run: |
        pr=$(curl -X POST -H "Authorization: Bearer ${{ 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 }}" -d '{"head":"development","base":"main","title":"Merge development to main"}' https://api.github.com/repos/${{ github.repository }}/pulls)
        echo "::set-output name=pull_request_number::$(echo $pr | jq -r '.number')"

    - name: Merge Pull Request
      run: |
        prNumber=${{ steps.create_pr.outputs.pull_request_number }}
        curl -X PUT -H "Authorization: Bearer ${{ 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 }}" "https://api.github.com/repos/${{ github.repository }}/pulls/${prNumber}/merge"
